### PR TITLE
Custom climate portraits with pyviz

### PR DESCRIPTION
**Pull request by aulemahal**
WIP of a "Custom Climate Portraits" app using Panel, Holoviews and Geoviews. 

At PR-making-time, we have a simple workflow of selecting a region, an indicator and options. (but no computation of any kind)

The environment.yml file has been modified.

Downloading and extracting the data via thredds is extremely slow, making it hard to test anything. 

@tlogan2000 @Zeitsperre  If you want to play with it too.

### CODE REVIEW

**Comment by tlogan2000** [comment]
I do want to play but am stuck doing other stuff :( ... We can check it out next week

**Comment by tlvu** [comment]
> Downloading and extracting the data via thredds is extremely slow, making it hard to test anything.

Just curious, I assume this is slow on the first attempt only?  On subsequent re-run, the same data has already been cached locally?

FYI @aulemahal I just merge your branch with master (so do a pull on your side) and I am building your branch to release a new devel docker image so everyone can try on Medus.

**Comment by aulemahal** [comment]
haha @tlvu I've never had the patience to wait for the completion of the first attempt, so I don't know.

**Comment by tlvu** [comment]
The new Jupyter image is available on Medus for everyone to try.

**Comment by tlvu** [comment]
Just pushed new build for the docker image to be in sync with new PR https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/43

**Comment by tlvu** [comment]
The new docker image is in prod.  You guys can use the production Jupyter https://pavics.ouranos.ca/jupyter to test/work.

**Comment by aulemahal** [comment]
IT NOW GOES ALL THE WAY TO THE GRAPHS!
But it is still ugly and certainly buggy.

**Comment by aulemahal** [comment]
@tlogan2000  FYI : I added comments and docstrings, I believe this is ready to be picked up by someone else!

**Comment by tlvu** [comment]
@aulemahal @tlogan2000 now that we have the new portrait climatique and analogues_spatiaux dashboard, is this branch still relevant?

**Comment by tlogan2000** [comment]
I don't think we want to lose this code but I don't know if this is the correct spot for this... Definitely not needed as a Jenkins option.  @aulemahal do we have a separate repo just for development of the 'custom' portrait idea?

**Comment by aulemahal** [comment]
Yes we do! https://github.com/Ouranosinc/custom_climate_portraits
I think we can close this branch.

**Comment by tlvu** [comment]
OK, closing.

**Pull request closed without merging**
