### PR TITLE
Jenkins: allow to programmatically override all params in Jenkinsfile

### PR DESCRIPTION
**Pull request by tlvu**
This new `CONFIG_PARAMETERS_SCRIPT_URL` is different than the previous `CONFIG_OVERRIDE_SCRIPT_URL` in that it overrides all the Jenkins params much sooner so all regular processing can take place.

When the regular processing are not enough and we need additional customizations, then we use the other `CONFIG_OVERRIDE_SCRIPT_URL`.

The two override scripts complement each other by hooking into the process at different moment in time, and together they allow full complete override of the various options for the test run.

Furthermore, `CONFIG_OVERRIDE_SCRIPT_URL` can also be a local file that is created on the fly by `CONFIG_PARAMETERS_SCRIPT_URL` so in the end, only `CONFIG_PARAMETERS_SCRIPT_URL` is needed for a full complete override.

### CODE REVIEW

**Review by fmigneault — COMMENTED** [review]
I can understand the use case, but I find the parameter naming very confusing. The `CONFIG_OVERRIDE_SCRIPT_URL` makes senses, because it can indeed "*override*" everything that was evaluated just before using the variables, but `JENKINS_CONFIG_OVERRIDE_SCRIPT_URL` does not override "that much" IMO.

For example, if `NOTEBOOKS_TO_TEST=my-notebook.ipynb` was set in the file referred by `JENKINS_CONFIG_OVERRIDE_SCRIPT_URL`, the value would be completely ignored. The only variables that can actually be "overridden" are the ones that are used directly (without setting them in the scripts), or that do a conscious self-check by reusing their value (such as for escaping values).

I would suggest using another name to make this distinction clearer. Maybe `CONFIG_PARAMETERS_SCRIPT_URL` or similar? Basically, avoiding the "override" mention.

**Comment by tlvu** [comment]
> I would suggest using another name to make this distinction clearer. Maybe `CONFIG_PARAMETERS_SCRIPT_URL` or similar? Basically, avoiding the "override" mention.

You are absolutely right.  The naming could be better.  Will do this.

**Comment by tlvu** [comment]
FYI, @fmigneault I added a new capability: `CONFIG_OVERRIDE_SCRIPT_URL` can also be a local file that is created on the fly by `CONFIG_PARAMETERS_SCRIPT_URL` so in the end, only `CONFIG_PARAMETERS_SCRIPT_URL` is needed for a full complete override.

**Review by mishaschwartz — APPROVED** [review]
Overall I like it. I don't have the experience with these files to comment on the details but it looks good in general.

**Pull request merged**
