### PR TITLE
docker: new build to remove salem, replaced by rioxarray and add packages for the custom_climate_portraits branch

### PR DESCRIPTION
**Pull request by tlvu**
Now we do not need a separate docker build for the [`custom_climate_portraits`](https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/tree/custom_climate_portraits) branch (PR https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/35).  That branch should only be used for notebook changes.  Jupyter env change should directly PR to `master`.

Did not add the full `holoviz` package since it seems to freeze the build (stuck in Solving Environment for more than 25 mins).

Also changed the base image to continuumio/miniconda3 since the previous one was deprecated.

Raven PR https://github.com/Ouranosinc/raven/pull/266 (commit https://github.com/Ouranosinc/raven/commit/0763bf52abec1bc0a70927de3a2dc2cc1cf77ec3) removed salem dependency and replaced with rioxarray.

salem was previously introduced in PR https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/36 (commit https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/commit/f916beadf8f9056e76ed88a52bdfb221c3ee7fb8).

Passing Jenkins build: http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/new-docker-image-to-remove-salem-replaced-by-rioxarray/lastSuccessfulBuild/console, new docker build: http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/new-docker-image-to-remove-salem-replaced-by-rioxarray/4/console

Jenkins build against Raven notebooks no import error http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/new-docker-image-to-remove-salem-replaced-by-rioxarray/3/consoleFull

Noticeable changes:
```diff
# conda release of bokeh seems to trail behind pypi 
>   - bokeh=2.0.1=py37hc8dfbb8_0
<     - bokeh==2.0.2 
>   - jupyter_bokeh=2.0.1=py_0

# should already exist, not sure why conda env export report this as new
>   - dask=2.15.0=py_0

# unpinned since salem is removed
<   - pandas=0.25.3=py37hb3f55d8_0
>   - pandas=1.0.3=py37h0da4684_1

<     - salem==0.2.4
>   - rioxarray=0.0.26=py_0

# packages for custom_climate_portraits branch
>   - geoviews=1.8.1=py_0
>   - h5netcdf=0.8.0=py_0
>   - holoviews=1.13.2=pyh9f0ad1d_0
>   - panel=0.9.5=py_1
>   - hvplot=0.5.2=py_0
>   - pscript=0.7.3=py_0
>   - siphon=0.8.0=py37_1002
>     - ipython-blocking==0.2.1
```

Full conda env export Diff:
[200427-200506-conda-env-export.diff.txt](https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/files/4590227/200427-200506-conda-env-export.diff.txt)

[200506-200507-conda-env-export.diff.txt](https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/files/4594860/200506-200507-conda-env-export.diff.txt)

Full new conda env export:
[200506-conda-env-export.yml.txt](https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/files/4590228/200506-conda-env-export.yml.txt)

[200507-conda-env-export.yml.txt](https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/files/4594861/200507-conda-env-export.yml.txt)

### CODE REVIEW

**Comment by aulemahal** [comment]
I remember having a hard time installing the holoviz ecosystem directly, but I'll try again today!

**Comment by aulemahal** [comment]
@tlvu @tlogan2000 With `-c pyviz` and package "holoviz",  "Solving Environment" as now been running for more than 20 minutes...  Maybe that's a problem in itself?

**Comment by tlogan2000** [comment]
> @tlvu @tlogan2000 With `-c pyviz` and package "holoviz", "Solving Environment" as now been running for more than 20 minutes... Maybe that's a problem in itself?

Ok forget my comment I guess.

**Comment by tlvu** [comment]
> we seem to be including almost everything other than hvplot, datashader(?) anyways

We already have `datashader=0.10.0=py_0`, see [200506-conda-env-export.yml.txt](https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/files/4590228/200506-conda-env-export.yml.txt) for all the packages in this build and their specific version.

> With `-c pyviz` and package "holoviz", "Solving Environment" as now been running for more than 20 minutes... Maybe that's a problem in itself?

Retrying on my side as well, but waiting for 20 mins, clearly a problem.  Probably because we install a lot of other stuff already in that 6GB docker image.

**Comment by tlogan2000** [comment]
I would actaully want to add hvplot as well I think..  Seems to provide some nice shortcuts for xarray plotting

https://hvplot.holoviz.org/

**Comment by tlvu** [comment]
Full holoviz package also froze my build, dropping that, just add hvplot for now.

**Comment by tlogan2000** [comment]
@tlvu don't we need this extension @pyviz/jupyterlab_pyviz in order to have interactive comms for the figures ?

https://github.com/holoviz/pyviz_comms

**Comment by tlvu** [comment]
> @tlvu don't we need this extension @pyviz/jupyterlab_pyviz in order to have interactive comms for the figures ?
> 
> https://github.com/holoviz/pyviz_comms

I tried adding it and it didn't build !  See my commit https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/44/commits/ce329a45b7c77daf5daec909dcb6e1225ca402f8

Also on the `custom_climate_portraits` branch, it's not there anyways so I thought it was not necessary https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/blob/b5359f6f6a545011d23f02f7441826cc05421efb/docker/Dockerfile#L36-L39

Will try to re-enable it next time I build this docker image again.

**Pull request merged**
