### PR TITLE
docker: adds 4 jupyterlab extensions

### PR DESCRIPTION
**Pull request by ChaamC**
Adds 4 jupyterlab extensions to the docker image : jupytext, jupyterlab-google-drive, jupyter_conda and jupyterlab-git

Relevant changes:
```diff
>   - jupyter_conda=3.4.1=pyh9f0ad1d_0
>   - jupyterlab-git=0.22.3=pyhd8ed1ab_0
>   - jupytext=1.6.0=pyh9f0ad1d_0

<   - jupyterhub=1.1.0=py38h32f6830_5
>   - jupyterhub=1.2.1=py38h578d9bd_0
```

Passing Jenkins build: http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/add-notebook-tools/9/console

Full `conda env export` diff:
[201026-201111-conda-env-export.diff.txt](https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/files/5527818/201026-201111-conda-env-export.diff.txt)

Full new `conda env export`:
[201111-conda-env-export.yml.txt](https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/files/5527819/201111-conda-env-export.yml.txt)

Matching PR https://github.com/bird-house/birdhouse-deploy/pull/97 for jupyterlab-google-drive config.

Matching PR https://github.com/Ouranosinc/pavics-sdi/pull/185 for documentation about the new extensions.

### CODE REVIEW

**Review by dbyrns — APPROVED** [review]

**Review by MatProv — APPROVED** [review]

**Review by tlvu — APPROVED** [review]
LGTM.  Thanks for the changes.

Just curious, are changes by the jupyter-conda extension persistent if user delete and recreate his jupyter container?  If not, is there a trace kept in his `$HOME` so he can easily re-create it again?

How is google drive credentials stored?  The `$HOME` of the user persist on disk, is this credential in clear text in there or under some form of hash.  Same credential privacy question for the jupyter-git if push/pull over SSH.

**Comment by ChaamC** [comment]
@tlvu @dbyrns 
> Just curious, are changes by the jupyter-conda extension persistent if user delete and recreate his jupyter container? If not, is there a trace kept in his `$HOME` so he can easily re-create it again?

Changes are not persistent. Restarting the server should reset the packages installed by the user. If the user wants to easily reproduce it, he could make his own .yml file that he can import with the extension to create a new environment. The user can also export his current environment to a .yml file to 'save' the state of his last session's environment and to reuse it later. 
Or he can still proceed with installing directly into a notebook cell. Installing packages within a cell will be reflected on the extension's packages list.
	

> How is google drive credentials stored? The `$HOME` of the user persist on disk, is this credential in clear text in there or under some form of hash. Same credential privacy question for the jupyter-git if push/pull over SSH.

- For the gdrive credentials, it seems only to be stored in the browser's cache, not in the $HOME.

- For git, it seems using the "git config credential.helper store" command for example would potentially expose the user's credentials in the home directory by creating a .git-credentials file with his info in it. Even if we block the terminal, the user can still use that command in a notebook cell.
I think there would be a way to block this on the 'global' and 'system' config levels using git's env variables, but I think the user could still override it by deciding to change the git local config in a repository.

I guess a way would be to prevent the user from using the 'git config' command entirely ? I don't know how easy it is to do this with the docker/jupyterhub environment though.

**Comment by tlvu** [comment]
We can merge this PR I think.  If there are extra config to tighten the security, it will have to be done in the birdhouse-deploy repo anyways.

Let me perform a build so we can release, because DockerHub once again is unable to build this image, see https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/issues/51 It's so annoying.

I'll merge this PR myself.

**Comment by ChaamC** [comment]
@tlvu 
Alright, I just added a warning for the git credentials in the documentation notebook (in pavics-sdi) for now.

**Pull request merged**
