### PR TITLE
New docker build for ravenpy birdy xclim

### PR DESCRIPTION
**Pull request by tlvu**
# Overview

New Jupyter env to get latest of everything, including ravenpy, birdy, xclim.

Jenkins build passing with updated Finch and Pavics-sdi notebooks: http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/new-docker-build-for-ravenpy/25/

Matching Finch notebook PR: https://github.com/bird-house/finch/pull/188
Matching Pavics-sdi notebook PR: https://github.com/Ouranosinc/pavics-sdi/pull/222
Matching PR to deploy this Jupyter env to PAVICS: https://github.com/bird-house/birdhouse-deploy/pull/175

Matching Raven notebook failure found https://github.com/Ouranosinc/raven/issues/392 (http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/new-docker-build-for-ravenpy/14/console) and matching fix PR https://github.com/Ouranosinc/raven/pull/393 (http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/new-docker-build-for-ravenpy/24/).

Also added new libraries for upcoming Raven notebooks (fixes https://github.com/Ouranosinc/raven/issues/394).

Pavics-landing homepage notebooks manually tested by @tlogan2000 

Deployed to staging env for manual testing: https://medus.ouranos.ca/jupyter/

Also added a way to quickly test a new package without having to do a full rebuild.

## Changes

```diff
<   - ravenpy=0.4.2=py37_1
>   - ravenpy=0.5.2=pyh7f9bfb9_0

# Renamed.
<   - raven=3.0.4.318=hc9bffa2_2
>   - raven-hydro=3.0.4.322=h516393e_0

<   - ostrich=21.03.16=h2bc3f7f_0
>   - ostrich=21.03.16=h4bd325d_1

<   - xclim=0.25.0=pyhd8ed1ab_0
>   - xclim=0.27.0=pyhd8ed1ab_0

# Old version was from pip.
<     - birdhouse-birdy==0.7.0
>   - birdy=v0.8.0=pyh6c4a22f_0

# Was previously included in another package, now it is standalone.
>   - pydantic=1.8.2=py37h5e8e339_0

# New libs for upcoming Raven notebooks
>   - gcsfs=2021.6.0=pyhd8ed1ab_0
>   - intake=0.6.2=pyhd8ed1ab_0
>   - intake-esm=2021.1.15=pyhd8ed1ab_0
>   - zarr=2.8.3=pyhd8ed1ab_0

<   - xarray=0.17.0=pyhd8ed1ab_0
>   - xarray=0.18.2=pyhd8ed1ab_0

<   - owslib=0.23.0=pyhd8ed1ab_0
>   - owslib=0.24.1=pyhd8ed1ab_0

<   - cf_xarray=0.5.1=pyh44b312d_0
>   - cf_xarray=0.5.2=pyh6c4a22f_0

<   - clisops=0.6.3=pyh44b312d_0
>   - clisops=0.6.5=pyh6c4a22f_0

<   - dask=2021.2.0=pyhd8ed1ab_0
>   - dask=2021.6.0=pyhd8ed1ab_0

# Downgrade !
<   - gdal=3.2.1=py37hc5bc4e4_7
>   - gdal=3.1.4=py37h2ec2946_8

# Downgrade !
<   - rasterio=1.2.2=py37hd5c4cce_0
>   - rasterio=1.2.1=py37ha549118_0

<   - hvplot=0.7.1=pyh44b312d_0
>   - hvplot=0.7.2=pyh6c4a22f_0

<   - rioxarray=0.3.1=pyhd8ed1ab_0
>   - rioxarray=0.4.1.post0=pyhd8ed1ab_0

# Downgrade !
<   - xskillscore=0.0.19=pyhd8ed1ab_0                                                                                                                 
>   - xskillscore=0.0.18=py_1
```

Full diff of `conda env export`:
[210415-210527.1-update210615-conda-env-export.diff.txt](https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/files/6658638/210415-210527.1-update210615-conda-env-export.diff.txt)

Full new `conda env export`:
[210527.1-update210615-conda-env-export.yml.txt](https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/files/6658646/210527.1-update210615-conda-env-export.yml.txt)

### CODE REVIEW

**Comment by aulemahal** [comment]
The update to `cftime==1.5.0` is supposed to break the notebooks of the PAVICS homepage, I gather they are not tested?

**Comment by tlvu** [comment]
> The update to `cftime==1.5.0` is supposed to break the notebooks of the PAVICS homepage, I gather they are not tested?

@aulemahal 
Nice catch, notebooks of PAVICS homepage are not part of regular test yet.  It's a private git repo so had trouble hooking it into the standard test.

What would be a possible work-around, pin cftime to the previous version?

@tlogan2000 We have to have a plan to ensure testing of the PAVICS homepage notebooks.  Each release of Jupyter env, I ask you to manually test them?  Make the pavics-landing git repo public so it's simple to plug into the existing testing mechanism?  Or I completely re-write the testing and tuto notebooks deployment to be able to handle private git repo?

**Comment by tlvu** [comment]
This new Jupyter env is deployed to staging env for manual testing: https://medus.ouranos.ca/jupyter/

**Comment by aulemahal** [comment]
As sad as it is, I think pinning `cftime` is the current solution. In fact, the problem arises from `nc-time-axis` (see SciTools/nc-time-axis#58). That's the small plugin that allows us to plot with matplotlib when the time axis is made of `cftime` objects (instead of numpy objects).

**Review by huard — APPROVED** [review]

**Comment by tlogan2000** [comment]
@tlvu  I think we can make probably make pavics-landing public.  Testing is definitely good idea but there are a couple of "advanced" sections that calculate a lot of data and take a while to run etc... we might need some precalculated data in the repo and a method to somehow skip a cell or two in a given notebook in the tests?  We can try set up a plan for sure

**Comment by tlvu** [comment]
New build with cftime pinning is on https://medus.ouranos.ca/jupyter/.  Many build problems on DockerHub today.

**Review by cjauvin — APPROVED** [review]

**Pull request merged**
