### PR TITLE
TEST - Pin xarray above 0.18.2

### LINKED ISSUE #77: Not able to pull latest RavenPy 0.6.0 in a full rebuild
Triggered a full rebuild on DockerHub today (https://hub.docker.com/repository/registry-1.docker.io/pavics/workflow-tests/builds/b5e792c8-0ad7-481a-a5d4-663494cd7c19) and RavenPy is still at `0.5.2` while the latest one on https://anaconda.org/conda-forge/ravenpy/ is `0.6.0`.

DockerHub build logs: [pavics-workflow-tests-builds-b5e792c8-0ad7-481a-a5d4-663494cd7c19.txt](https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/files/6679192/pavics-workflow-tests-builds-b5e792c8-0ad7-481a-a5d4-663494cd7c19.txt)

It's as if some indirect dependency in the environment.yml file (https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/blob/1ce2e5445600be8808fa9282b95034986ade6aea/docker/environment.yml) pinned RavenPy version.

Tried forcing `ravenpy==0.6.0` and stuck at dependency solving:
```
$ docker run -it --rm --name test-ravenpy-pinning -u 0 --entrypoint bash pavics/workflow-tests:210527.1-update20210618
(base) root@f71b6fb1f025:/# conda activate birdy
(birdy) root@f71b6fb1f025:/# conda install -c conda-forge -c cdat -c bokeh -c plotly -c defaults -n birdy ravenpy==0.6.0
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: /-
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
```

FYI @Zeitsperre

### PR DESCRIPTION
**Pull request by Zeitsperre**
# Overview

Please include a summary of the changes and which issues are fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

This PR fixes #77 

## Changes

- Pins xarray above 0.18 so that the latest `ravenpy` is pulled.

## Related Issue / Discussion

- Resolves ...

## Additional Information

Links to other issues or sources.

- [ ] Things to do...

### CODE REVIEW

**Comment by tlvu** [comment]
Triggered build https://hub.docker.com/repository/registry-1.docker.io/pavics/workflow-tests/builds/702975fb-a88b-4fab-ae8c-617d47296f85 on Dockerher, unfortunately it still pulled the old RavenPy 0.5.2.

**Comment by Zeitsperre** [comment]
Do we need to pin Ravenpy at 6.0.0? I can't figure out why it defaults to the older version.

**Comment by tlvu** [comment]
In the issue #77, I also attempted to pin ravenpy==0.6.0 in an incremental build and it didn't work.  But we can try a full build see what happens.

**Comment by tlvu** [comment]
Close not merged since a different fix https://github.com/conda-forge/ravenpy-feedstock/pull/7 fixed this.

**Pull request closed without merging**
