### PR TITLE
New Jupyter env docker build for urlpath

### PR DESCRIPTION
**Pull request by tlvu**
# Overview

Full rebuild to add `urlpath`.  Previous rebuild was https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/106.

## Changes

- Adds `urlpath` for https://github.com/Ouranosinc/pavics-sdi/pull/268, fixes https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/issues/110
- Relevant changes (alphabetical order):
```diff
<   - climpred=2.2.0=pyhd8ed1ab_0
>   - climpred=2.3.0=pyhd8ed1ab_0

<   - dask=2022.11.0=pyhd8ed1ab_0
>   - dask=2022.11.1=pyhd8ed1ab_0

<   - flox=0.6.3=pyhd8ed1ab_0
>   - flox=0.6.4=pyhd8ed1ab_0

<   - h5netcdf=1.0.2=pyhd8ed1ab_0
>   - h5netcdf=1.1.0=pyhd8ed1ab_0

<   - numpy=1.23.4=py38h7042d01_1
>   - numpy=1.23.5=py38h7042d01_0

>   - urlpath=1.2.0=pyhd8ed1ab_0
```

## Test

- Deployed as "alpha" image in production for bokeh visualization performance regression testing.

- Manual test notebook https://github.com/Ouranosinc/PAVICS-landing/blob/master/content/notebooks/climate_indicators/PAVICStutorial_ClimateDataAnalysis-5Visualization.ipynb for bokeh visualization performance and it looks fine.

- Jenkins build: all passed except known esgf-dap.ipynb:
[job-PAVICS-e2e-workflow-tests-new-docker-build-121-consoleText.txt](https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/files/10232109/job-PAVICS-e2e-workflow-tests-new-docker-build-121-consoleText.txt)

## Related Issue / Discussion

- Deployment to PAVICS: https://github.com/bird-house/birdhouse-deploy/pull/271

## Additional Information

- Full diff `conda env export`:
[221118.1-221130-conda-env-export.diff.txt](https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/files/10232126/221118.1-221130-conda-env-export.diff.txt)

- Full new `conda env export`:
[221130-conda-env-export.yml.txt](https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/files/10232133/221130-conda-env-export.yml.txt)

- DockerHub build logs:
[Dockerhub-buildlogs-pavics-workflow-tests-221130.txt](https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/files/10232160/Dockerhub-buildlogs-pavics-workflow-tests-221130.txt)

### CODE REVIEW

**Review by huard — APPROVED** [review]

**Comment by huard** [comment]
Trevor mentioned another library to deal with URLs (yarl), but I suggest we go ahead with urlpath for the time being. Functionalities seem very similar.

**Comment by Zeitsperre** [comment]
I haven't had a chance to look at it, but yarl seems be safer (non-mutable objects), and maintained. I'll work it into some existing projects first to get a sense of it. We can move from urlpath eventually.

**Comment by tlvu** [comment]
@huard a build with `urlpath` is available on PAVICS as the `alpha` Jupyter image.  You can try your notebooks.  I'll try to close this PR for this week.  All initial tests seem fine with this new build so far.

**Comment by tlvu** [comment]
@tlogan2000 @JeremyFyke FYI a new Jupyter env is coming.  Delta vs the previous release is fairly small since they differ for 2 weeks only.

All standard checks are passing.  I guess it should not break the various Panel dashboard we have but I have not checked.  It is deployed currently as `alpha` image on PAVICS.  Schedule to go-live this Friday.

**Comment by tlvu** [comment]
@tlogan2000 This new Jupyter env is live.  I decided to keep the existing "previous" release in the Jupyter image drop-down menu unchanged since the change between this one and the previous release is fairly small.

**Comment by tlogan2000** [comment]
Excellent! Thanks @tlvu

**Comment by JeremyFyke** [comment]
Hi @tlvu - can you confirm which PAVICS version to test apps out against?  the fire weather app works in internal testing but appears to error out upon deployment (tested against alpha, beta, current, and panel_dashboard).

**Comment by tlvu** [comment]
> Hi @tlvu - can you confirm which PAVICS version to test apps out against? the fire weather app works in internal testing but appears to error out upon deployment (tested against alpha, beta, current, and panel_dashboard).

@JeremyFyke Fixed in https://github.com/Ouranosinc/pavics_panel_cccs_deploy/pull/11

As for which image, it is the current image.  You can always refer to the source of truth here https://github.com/Ouranosinc/pavics_panel_cccs_deploy/blob/4563f94944dafe83783cc3c9c12da6a027891a98/cccs-config/docker-compose-extra.yml#L56-L57

**Pull request merged**
